export interface AttendanceRecord {
  id: string;
  no: number;
  period_month: string; // Format: YYYY-MM (e.g. "2026-08")
  employee_no: string;
  name: string;
  date: string;
  shift: string;
  start_time: string;
  end_time: string;
  status: string;
  overtime: number;
  overtime_index: string;
  created_at?: string;
}

export function extractPeriodMonth(dateStr: string): string {
  if (!dateStr) return "";
  const text = String(dateStr).trim();

  // 1. ISO format: 2026-08-31
  const isoMatch = text.match(/^(\d{4})[-/](\d{1,2})/);
  if (isoMatch) {
    return `${isoMatch[1]}-${isoMatch[2].padStart(2, "0")}`;
  }

  // 2. DD/MM/YYYY or DD-MM-YYYY format: 31/08/2026
  const dmyMatch = text.match(/^\d{1,2}[-/](\d{1,2})[-/](\d{4})/);
  if (dmyMatch) {
    return `${dmyMatch[2]}-${dmyMatch[1].padStart(2, "0")}`;
  }

  // 3. Text date: "Mon, 31 Aug 2026" or "31 Agustus 2026"
  const monthMap: Record<string, string> = {
    jan: "01", feb: "02", mar: "03", apr: "04", may: "05", mei: "05",
    jun: "06", jul: "07", aug: "08", agu: "08", sep: "09", okt: "10",
    oct: "10", nov: "11", nop: "11", des: "12", dec: "12",
  };

  const yearMatch = text.match(/\b(20\d{2})\b/);
  const year = yearMatch ? yearMatch[1] : "";

  for (const [k, v] of Object.entries(monthMap)) {
    const re = new RegExp(`\\b${k}`, "i");
    if (re.test(text)) {
      return year ? `${year}-${v}` : "";
    }
  }

  return "";
}

export function formatPeriodMonth(period: string): string {
  if (!period || !period.includes("-")) return period || "-";
  const [year, month] = period.split("-");
  const monthNames: Record<string, string> = {
    "01": "Januari",
    "02": "Februari",
    "03": "Maret",
    "04": "April",
    "05": "Mei",
    "06": "Juni",
    "07": "Juli",
    "08": "Agustus",
    "09": "September",
    "10": "Oktober",
    "11": "November",
    "12": "Desember",
  };
  return `${monthNames[month] || month} ${year}`;
}

const RAW_INITIAL_DATA: Omit<AttendanceRecord, "period_month">[] = [
  {
    id: "att-1",
    no: 1,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Mon, 31 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:54",
    end_time: "17:04",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-2",
    no: 2,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Mon, 31 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:17",
    end_time: "21:11",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-3",
    no: 3,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sun, 30 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-4",
    no: 4,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sun, 30 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-5",
    no: 5,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sat, 29 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-6",
    no: 6,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sat, 29 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-7",
    no: 7,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Fri, 28 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:52",
    end_time: "17:18",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-8",
    no: 8,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Fri, 28 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:07",
    end_time: "17:26",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-9",
    no: 9,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Thu, 27 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:56",
    end_time: "17:07",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-10",
    no: 10,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Thu, 27 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:23",
    end_time: "17:32",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-11",
    no: 11,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Wed, 26 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:44",
    end_time: "17:04",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-12",
    no: 12,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Wed, 26 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:16",
    end_time: "17:22",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-13",
    no: 13,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Tue, 25 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-14",
    no: 14,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Tue, 25 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-15",
    no: 15,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Mon, 24 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "-",
    end_time: "-",
    status: "ABS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-16",
    no: 16,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Mon, 24 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:11",
    end_time: "21:17",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-17",
    no: 17,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sun, 23 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-18",
    no: 18,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sun, 23 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-19",
    no: 19,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sat, 22 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-20",
    no: 20,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sat, 22 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-21",
    no: 21,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Fri, 21 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:32",
    end_time: "17:03",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-22",
    no: 22,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Fri, 21 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:20",
    end_time: "18:02",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-23",
    no: 23,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Thu, 20 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:53",
    end_time: "17:04",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-24",
    no: 24,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Thu, 20 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:10",
    end_time: "18:09",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-25",
    no: 25,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Wed, 19 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:56",
    end_time: "18:18",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-26",
    no: 26,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Wed, 19 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:15",
    end_time: "18:29",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-27",
    no: 27,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Tue, 18 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:53",
    end_time: "17:04",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-28",
    no: 28,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Tue, 18 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:13",
    end_time: "17:27",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-29",
    no: 29,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Mon, 17 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-30",
    no: 30,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Mon, 17 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-31",
    no: 31,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sun, 16 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-32",
    no: 32,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sun, 16 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-33",
    no: 33,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sat, 15 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-34",
    no: 34,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sat, 15 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-35",
    no: 35,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Fri, 14 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:49",
    end_time: "17:33",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-36",
    no: 36,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Fri, 14 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:15",
    end_time: "17:40",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-37",
    no: 37,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Thu, 13 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:51",
    end_time: "17:02",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-38",
    no: 38,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Thu, 13 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:16",
    end_time: "21:35",
    status: "EAI,OVT,PRS",
    overtime: 180,
    overtime_index: "5,5",
  },
  {
    id: "att-39",
    no: 39,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Wed, 12 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:48",
    end_time: "17:04",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-40",
    no: 40,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Wed, 12 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:15",
    end_time: "17:52",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-41",
    no: 41,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Tue, 11 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:48",
    end_time: "17:23",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-42",
    no: 42,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Tue, 11 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:19",
    end_time: "17:43",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-43",
    no: 43,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Mon, 10 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:52",
    end_time: "17:11",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-44",
    no: 44,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Mon, 10 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "06:58",
    end_time: "21:45",
    status: "EAI,OVT,PRS",
    overtime: 180,
    overtime_index: "5,5",
  },
  {
    id: "att-45",
    no: 45,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sun, 09 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-46",
    no: 46,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sun, 09 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-47",
    no: 47,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sat, 08 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-48",
    no: 48,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sat, 08 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-49",
    no: 49,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Fri, 07 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:00",
    end_time: "17:02",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-50",
    no: 50,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Fri, 07 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "06:39",
    end_time: "17:50",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-51",
    no: 51,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Thu, 06 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:53",
    end_time: "17:03",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-52",
    no: 52,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Thu, 06 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:16",
    end_time: "17:20",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-53",
    no: 53,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Wed, 05 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:51",
    end_time: "17:01",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-54",
    no: 54,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Wed, 05 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:19",
    end_time: "17:14",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-55",
    no: 55,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Tue, 04 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:51",
    end_time: "17:15",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-56",
    no: 56,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Tue, 04 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:16",
    end_time: "17:27",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-57",
    no: 57,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Mon, 03 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:45",
    end_time: "17:03",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-58",
    no: 58,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Mon, 03 Aug 2026",
    shift: "Shift Daily from 08:00 to 17:00",
    start_time: "07:10",
    end_time: "17:32",
    status: "EAI,PRS",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-59",
    no: 59,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sun, 02 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-60",
    no: 60,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sun, 02 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-61",
    no: 61,
    employee_no: "GIS25100212",
    name: "Muhammad  Farel Ramadhan",
    date: "Sat, 01 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
  {
    id: "att-62",
    no: 62,
    employee_no: "GIS19040039",
    name: "Paulus Petrus Parlindungan Sianipar",
    date: "Sat, 01 Aug 2026",
    shift: "Shift OFF",
    start_time: "-",
    end_time: "-",
    status: "OFF",
    overtime: 0,
    overtime_index: "0",
  },
];

export const INITIAL_ATTENDANCE_DATA: AttendanceRecord[] = RAW_INITIAL_DATA.map((item) => ({
  ...item,
  period_month: extractPeriodMonth(item.date) || "2026-08",
}));

/**
 * Buat data presensi baseline untuk 1 periode bulan tertentu (Paulus & Farel)
 * jika database belum memiliki catatan presensi untuk bulan tersebut.
 */
export function getAttendanceSeedForPeriod(period: string): AttendanceRecord[] {
  if (period === "2026-08") {
    return INITIAL_ATTENDANCE_DATA;
  }

  const [yearStr, monthStr] = period.split("-");
  const year = parseInt(yearStr, 10);
  const month = parseInt(monthStr, 10);
  if (!year || !month || month < 1 || month > 12) {
    return [];
  }

  const daysInMonth = new Date(year, month, 0).getDate();
  const records: AttendanceRecord[] = [];
  const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const monthNamesShort = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  let noCounter = 1;
  // Urutkan dari hari terakhir ke hari pertama sesuai format standar attendance
  for (let d = daysInMonth; d >= 1; d--) {
    const dateObj = new Date(year, month - 1, d);
    const dayOfWeek = dateObj.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    const dateFormatted = `${dayNames[dayOfWeek]}, ${String(d).padStart(2, "0")} ${monthNamesShort[month - 1]} ${year}`;

    // Paulus
    records.push({
      id: `att-${period}-p-${d}`,
      no: noCounter++,
      period_month: period,
      employee_no: "GIS19040039",
      name: "Paulus Petrus Parlindungan Sianipar",
      date: dateFormatted,
      shift: isWeekend ? "Shift OFF" : "Shift Daily from 08:00 to 17:00",
      start_time: isWeekend ? "-" : "07:35",
      end_time: isWeekend ? "-" : "17:15",
      status: isWeekend ? "OFF" : "EAI,PRS",
      overtime: !isWeekend && (d === 15 || d === 28) ? 60 : 0,
      overtime_index: "0",
    });

    // Farel
    records.push({
      id: `att-${period}-f-${d}`,
      no: noCounter++,
      period_month: period,
      employee_no: "GIS25100212",
      name: "Muhammad Farel Ramadhan",
      date: dateFormatted,
      shift: isWeekend ? "Shift OFF" : "Shift Daily from 08:00 to 17:00",
      start_time: isWeekend ? "-" : "07:55",
      end_time: isWeekend ? "-" : "17:10",
      status: isWeekend ? "OFF" : "EAI,PRS",
      overtime: !isWeekend && (d === 10 || d === 24) ? 60 : 0,
      overtime_index: "0",
    });
  }

  return records;
}

/**
 * Dapatkan seluruh data presensi baseline 12 bulan
 */
export function getAllAttendanceSeedData(year: number = 2026): AttendanceRecord[] {
  const result: AttendanceRecord[] = [];
  for (let m = 1; m <= 12; m++) {
    const period = `${year}-${String(m).padStart(2, "0")}`;
    result.push(...getAttendanceSeedForPeriod(period));
  }
  return result;
}

